- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "libxslt1-dev"
    - "libxslt1.1"
    - "libxml2-dev"
    - "libxml2"
    - "libssl-dev"
    - "libffi-dev"
    - "python-setuptools"
    - "python-pip"
    - "python-dev"
    - "libssl-dev"
    - "git"
    - "unrar"
    - "build-essential"
- name: Install pyopenssl dependency from pip
  pip:
    name: "pyopenssl"
- name: Install Sickrage
  git:
    repo: "https://github.com/SickRage/SickRage.git"
    dest: /opt/sickrage
- name: Create Sickrage user
  user:
    name: sickrage
    system: yes
- name: Asign ownershipt og sickrage to sickrage user
  file:
    path: "/opt/sickrage"
    owner: sickrage
    recurse: yes
